//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfClient.Service1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllWorkers", ReplyAction="http://tempuri.org/IService1/GetAllWorkersResponse")]
        prac1ASPNetBasics.Entities.Worker[] GetAllWorkers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetWorkerById", ReplyAction="http://tempuri.org/IService1/GetWorkerByIdResponse")]
        prac1ASPNetBasics.Entities.Worker GetWorkerById(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/EditWorkerById", ReplyAction="http://tempuri.org/IService1/EditWorkerByIdResponse")]
        void EditWorkerById(int id, string surname, string name, prac1ASPNetBasics.Entities.Address address, string phone, string position, int unitId, string head);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : WcfClient.Service1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WcfClient.Service1.IService1>, WcfClient.Service1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public prac1ASPNetBasics.Entities.Worker[] GetAllWorkers() {
            return base.Channel.GetAllWorkers();
        }
        
        public prac1ASPNetBasics.Entities.Worker GetWorkerById(int id) {
            return base.Channel.GetWorkerById(id);
        }
        
        public void EditWorkerById(int id, string surname, string name, prac1ASPNetBasics.Entities.Address address, string phone, string position, int unitId, string head) {
            base.Channel.EditWorkerById(id, surname, name, address, phone, position, unitId, head);
        }
    }
}
