//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AsmxClient.AsmxWorkerService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Worker", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Worker : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int WorkerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private AsmxClient.AsmxWorkerService.Address AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PositionField;
        
        private int UnitIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HeadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int WorkerId {
            get {
                return this.WorkerIdField;
            }
            set {
                if ((this.WorkerIdField.Equals(value) != true)) {
                    this.WorkerIdField = value;
                    this.RaisePropertyChanged("WorkerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AsmxClient.AsmxWorkerService.Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Position {
            get {
                return this.PositionField;
            }
            set {
                if ((object.ReferenceEquals(this.PositionField, value) != true)) {
                    this.PositionField = value;
                    this.RaisePropertyChanged("Position");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int UnitId {
            get {
                return this.UnitIdField;
            }
            set {
                if ((this.UnitIdField.Equals(value) != true)) {
                    this.UnitIdField = value;
                    this.RaisePropertyChanged("UnitId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Head {
            get {
                return this.HeadField;
            }
            set {
                if ((object.ReferenceEquals(this.HeadField, value) != true)) {
                    this.HeadField = value;
                    this.RaisePropertyChanged("Head");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        private int BuildingNumberField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Country {
            get {
                return this.CountryField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryField, value) != true)) {
                    this.CountryField = value;
                    this.RaisePropertyChanged("Country");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int BuildingNumber {
            get {
                return this.BuildingNumberField;
            }
            set {
                if ((this.BuildingNumberField.Equals(value) != true)) {
                    this.BuildingNumberField = value;
                    this.RaisePropertyChanged("BuildingNumber");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AsmxWorkerService.AsmxWorkerServiceSoap")]
    public interface AsmxWorkerServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAllWorkersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkers", ReplyAction="*")]
        AsmxClient.AsmxWorkerService.GetAllWorkersResponse GetAllWorkers(AsmxClient.AsmxWorkerService.GetAllWorkersRequest request);
        
        // CODEGEN: Generating message contract since element name GetWorkerByIdResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWorkerById", ReplyAction="*")]
        AsmxClient.AsmxWorkerService.GetWorkerByIdResponse GetWorkerById(AsmxClient.AsmxWorkerService.GetWorkerByIdRequest request);
        
        // CODEGEN: Generating message contract since element name surname from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditWorkerById", ReplyAction="*")]
        AsmxClient.AsmxWorkerService.EditWorkerByIdResponse EditWorkerById(AsmxClient.AsmxWorkerService.EditWorkerByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkers", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.GetAllWorkersRequestBody Body;
        
        public GetAllWorkersRequest() {
        }
        
        public GetAllWorkersRequest(AsmxClient.AsmxWorkerService.GetAllWorkersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllWorkersRequestBody {
        
        public GetAllWorkersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkersResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.GetAllWorkersResponseBody Body;
        
        public GetAllWorkersResponse() {
        }
        
        public GetAllWorkersResponse(AsmxClient.AsmxWorkerService.GetAllWorkersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWorkersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxClient.AsmxWorkerService.Worker[] GetAllWorkersResult;
        
        public GetAllWorkersResponseBody() {
        }
        
        public GetAllWorkersResponseBody(AsmxClient.AsmxWorkerService.Worker[] GetAllWorkersResult) {
            this.GetAllWorkersResult = GetAllWorkersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkerById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.GetWorkerByIdRequestBody Body;
        
        public GetWorkerByIdRequest() {
        }
        
        public GetWorkerByIdRequest(AsmxClient.AsmxWorkerService.GetWorkerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWorkerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetWorkerByIdRequestBody() {
        }
        
        public GetWorkerByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWorkerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWorkerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.GetWorkerByIdResponseBody Body;
        
        public GetWorkerByIdResponse() {
        }
        
        public GetWorkerByIdResponse(AsmxClient.AsmxWorkerService.GetWorkerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWorkerByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public AsmxClient.AsmxWorkerService.Worker GetWorkerByIdResult;
        
        public GetWorkerByIdResponseBody() {
        }
        
        public GetWorkerByIdResponseBody(AsmxClient.AsmxWorkerService.Worker GetWorkerByIdResult) {
            this.GetWorkerByIdResult = GetWorkerByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditWorkerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditWorkerById", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.EditWorkerByIdRequestBody Body;
        
        public EditWorkerByIdRequest() {
        }
        
        public EditWorkerByIdRequest(AsmxClient.AsmxWorkerService.EditWorkerByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditWorkerByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string surname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public AsmxClient.AsmxWorkerService.Address address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string position;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int unitId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string head;
        
        public EditWorkerByIdRequestBody() {
        }
        
        public EditWorkerByIdRequestBody(int id, string surname, string name, AsmxClient.AsmxWorkerService.Address address, string phone, string position, int unitId, string head) {
            this.id = id;
            this.surname = surname;
            this.name = name;
            this.address = address;
            this.phone = phone;
            this.position = position;
            this.unitId = unitId;
            this.head = head;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditWorkerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditWorkerByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public AsmxClient.AsmxWorkerService.EditWorkerByIdResponseBody Body;
        
        public EditWorkerByIdResponse() {
        }
        
        public EditWorkerByIdResponse(AsmxClient.AsmxWorkerService.EditWorkerByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class EditWorkerByIdResponseBody {
        
        public EditWorkerByIdResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AsmxWorkerServiceSoapChannel : AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AsmxWorkerServiceSoapClient : System.ServiceModel.ClientBase<AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap>, AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap {
        
        public AsmxWorkerServiceSoapClient() {
        }
        
        public AsmxWorkerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AsmxWorkerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxWorkerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AsmxWorkerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.AsmxWorkerService.GetAllWorkersResponse AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap.GetAllWorkers(AsmxClient.AsmxWorkerService.GetAllWorkersRequest request) {
            return base.Channel.GetAllWorkers(request);
        }
        
        public AsmxClient.AsmxWorkerService.Worker[] GetAllWorkers() {
            AsmxClient.AsmxWorkerService.GetAllWorkersRequest inValue = new AsmxClient.AsmxWorkerService.GetAllWorkersRequest();
            inValue.Body = new AsmxClient.AsmxWorkerService.GetAllWorkersRequestBody();
            AsmxClient.AsmxWorkerService.GetAllWorkersResponse retVal = ((AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap)(this)).GetAllWorkers(inValue);
            return retVal.Body.GetAllWorkersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.AsmxWorkerService.GetWorkerByIdResponse AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap.GetWorkerById(AsmxClient.AsmxWorkerService.GetWorkerByIdRequest request) {
            return base.Channel.GetWorkerById(request);
        }
        
        public AsmxClient.AsmxWorkerService.Worker GetWorkerById(int id) {
            AsmxClient.AsmxWorkerService.GetWorkerByIdRequest inValue = new AsmxClient.AsmxWorkerService.GetWorkerByIdRequest();
            inValue.Body = new AsmxClient.AsmxWorkerService.GetWorkerByIdRequestBody();
            inValue.Body.id = id;
            AsmxClient.AsmxWorkerService.GetWorkerByIdResponse retVal = ((AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap)(this)).GetWorkerById(inValue);
            return retVal.Body.GetWorkerByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AsmxClient.AsmxWorkerService.EditWorkerByIdResponse AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap.EditWorkerById(AsmxClient.AsmxWorkerService.EditWorkerByIdRequest request) {
            return base.Channel.EditWorkerById(request);
        }
        
        public void EditWorkerById(int id, string surname, string name, AsmxClient.AsmxWorkerService.Address address, string phone, string position, int unitId, string head) {
            AsmxClient.AsmxWorkerService.EditWorkerByIdRequest inValue = new AsmxClient.AsmxWorkerService.EditWorkerByIdRequest();
            inValue.Body = new AsmxClient.AsmxWorkerService.EditWorkerByIdRequestBody();
            inValue.Body.id = id;
            inValue.Body.surname = surname;
            inValue.Body.name = name;
            inValue.Body.address = address;
            inValue.Body.phone = phone;
            inValue.Body.position = position;
            inValue.Body.unitId = unitId;
            inValue.Body.head = head;
            AsmxClient.AsmxWorkerService.EditWorkerByIdResponse retVal = ((AsmxClient.AsmxWorkerService.AsmxWorkerServiceSoap)(this)).EditWorkerById(inValue);
        }
    }
}
